#ifndef PC_CONFIG_DEFINES
#define PC_CONFIG_DEFINES

#define CONFIG_SSID
#define CONFIG_PASSWORD
#define CONFIG_MQTT_SERVER
#define CONFIG_MQTT_PORT
#define CONFIG_MQTT_USER
#define CONFIG_MQTT_PASS
#define CONFIG_HOSTNAME
#define CONFIG_TX315
#define CONFIG_TX433
#define CONFIG_PUMP
#define CONFIG_FOUNTAIN
#define CONFIG_POOL_LIGHT
#define CONFIG_POOL_CHANNEL
#define CONFIG_AIR_CHANNEL
#define CONFIG_PRESSURE_CHANNEL

#endif